# Generated by Django 5.1.1 on 2024-10-02 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('entity_ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('fund', models.CharField(max_length=255)),
                ('posPre', models.CharField(max_length=255)),
                ('ledger_account', models.BigIntegerField()),
                ('heading', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('official_ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('number_ID', models.BigIntegerField(editable=False, validators=[django.core.validators.RegexValidator(message='El ID oficial solo puede contener números.', regex='^\\d+$')])),
                ('names', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras.', regex='^[a-zA-Z\\s]+$')])),
                ('last_names', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Los apellidos solo pueden contener letras.', regex='^[a-zA-Z\\s]+$')])),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='La ciudad solo puede contener números.', regex='^\\d+$')])),
                ('departament', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El departamento solo puede contener números.', regex='^\\d+$')])),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.BigIntegerField(null=True, validators=[django.core.validators.RegexValidator(message='El teléfono fijo solo puede contener números.', regex='^\\d+$')])),
                ('celphone', models.BigIntegerField(null=True, validators=[django.core.validators.RegexValidator(message='El celular solo puede contener números.', regex='^\\d+$')])),
                ('start_date', models.DateField()),
                ('entity_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesantias.entities')),
            ],
        ),
        migrations.CreateModel(
            name='NoWorkDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_work_days', models.IntegerField()),
                ('update_date', models.DateField(null=True)),
                ('request_ID', models.IntegerField(null=True)),
                ('official_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesantias.official')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('request_state', models.IntegerField(choices=[(1, 'RADICADA'), (2, 'LIQUIDADA'), (3, 'CDP SOLICITADO'), (4, 'EMISION RESOLUCION'), (5, 'NOTIFICADO'), (6, 'RPC SOLICITADO'), (7, 'RPC EMITIDO'), (8, 'PASO A FACTURACION'), (9, 'PROCESO DE PAGO'), ('10', 'RECHAZADO')])),
                ('filling_number', models.BigIntegerField()),
                ('filling_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('severance_type', models.CharField(choices=[('D', 'DEFINITIVA'), ('M', 'MONTO'), ('P', 'PARCIAL'), ('R', 'RELIQUIDACION')], max_length=1)),
                ('withdrawal_mode', models.CharField(choices=[('D', 'DEFINITIVA'), ('E', 'EDUCACION'), ('H', 'HIPOTECARIO'), ('O', 'TROS'), ('L', 'REPARACIONES LOCATIVAS'), ('C', 'COMPRA VIVIENDA')], max_length=1)),
                ('total_days', models.IntegerField(null=True)),
                ('no_work_days', models.IntegerField(null=True)),
                ('working_days', models.IntegerField(null=True)),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_severance_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('previous_severance_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('balance_severance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('severance_disbursed_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('settlement_date', models.DateField(null=True)),
                ('cdp_request_date', models.DateField(null=True)),
                ('cdp_issue_date', models.DateField(null=True)),
                ('cdp_number', models.BigIntegerField(null=True)),
                ('holder_position', models.CharField(max_length=255, null=True)),
                ('incharge_position', models.CharField(max_length=255, null=True)),
                ('notify_date', models.DateField(null=True)),
                ('resolution_date', models.DateField(null=True)),
                ('resolution_number', models.BigIntegerField(null=True)),
                ('rpc_request_date', models.DateField(null=True)),
                ('rpc_number', models.BigIntegerField(null=True)),
                ('billing_date', models.DateField(null=True)),
                ('treasury_date', models.DateField(null=True)),
                ('billing_number', models.BigIntegerField(null=True)),
                ('rejection_reason', models.TextField(null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('creation_user', models.CharField(max_length=255, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=255, null=True)),
                ('official_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesantias.official')),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.IntegerField()),
                ('cert_date', models.DateField()),
                ('cert_number', models.IntegerField(null=True)),
                ('cert_name', models.CharField(max_length=255, null=True)),
                ('cert_position', models.CharField(max_length=255, null=True)),
                ('cert_entity_name', models.CharField(max_length=255, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cesantias.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.IntegerField()),
                ('sell_seller', models.CharField(max_length=255, null=True)),
                ('sell_doc_type', models.CharField(max_length=255, null=True)),
                ('sell_doc_num', models.CharField(max_length=255, null=True)),
                ('def_resolution', models.CharField(max_length=255, null=True)),
                ('def_date', models.DateField(null=True)),
                ('def_position', models.CharField(max_length=255, null=True)),
                ('est_nit', models.CharField(max_length=255, null=True)),
                ('est_institution', models.CharField(max_length=255, null=True)),
                ('hip_loan_number', models.CharField(max_length=255, null=True)),
                ('hip_nit', models.CharField(max_length=255, null=True)),
                ('hip_bank', models.CharField(max_length=255, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cesantias.request')),
            ],
        ),
        migrations.CreateModel(
            name='WageFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('overwage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('annual_bonus', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('holiday_bonus', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('christmas_bonus', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transport_subsidy', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('food_subsidy', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('technical_bonus', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('seniority_bonus', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('accommodation_bonus', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('overtime', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dev_by_draw', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('travel_expenses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_factors', to='cesantias.request')),
            ],
        ),
    ]
