# Generated by Django 5.1.1 on 2024-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesantias', '0002_alter_official_celphone_alter_official_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='average_salary',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='balance_severance',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='filling_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='previous_severance_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='severance_disbursed_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='total_severance_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
