# Generated by Django 5.1.1 on 2024-10-04 23:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesantias', '0003_alter_request_average_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(max_length=100, unique=True)),
                ('depto_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='certifications',
            name='cert_number',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='number_ID',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='El ID oficial solo puede contener números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='request',
            name='filling_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='withdrawal_mode',
            field=models.CharField(choices=[('D', 'DEFINITIVA'), ('E', 'EDUCACION'), ('H', 'HIPOTECARIO'), ('O', 'OTROS'), ('R', 'REPARACIONES LOCATIVAS'), ('V', 'COMPRA VIVIENDA')], max_length=1),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=255)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cesantias.departament', to_field='departament')),
            ],
        ),
    ]
