# Generated by Django 5.1.1 on 2024-10-05 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesantias', '0004_departament_alter_certifications_cert_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='Extensions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='celphone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citdep', to='cesantias.city', to_field='city'),
        ),
        migrations.AlterField(
            model_name='official',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depto', to='cesantias.departament', to_field='departament'),
        ),
        migrations.AlterField(
            model_name='official',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
