# Generated by Django 5.1.1 on 2024-10-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesantias', '0005_official_extensions_alter_city_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official',
            old_name='Extensions',
            new_name='extensions',
        ),
    ]
