# Generated by Django 5.1.1 on 2024-10-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesantias', '0007_remove_requestdetail_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='cert_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='official_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cesantias.official'),
        ),
    ]
