# Generated by Django 5.1.1 on 2024-10-07 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesantias', '0008_alter_certifications_cert_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cesantias.request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='official_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesantias.official'),
        ),
    ]
