# Generated by Django 5.1.2 on 2024-11-06 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesantias', '0010_alter_noworkdays_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='filling_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='no_work_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='resolution_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
