# Generated by Django 5.1.2 on 2024-11-23 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesantias', '0011_alter_request_filling_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cutoff_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certifications',
            name='cert_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='resolution_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='severance_type',
            field=models.CharField(choices=[('D', 'DEFINITIVA'), ('P', 'PARCIAL')], max_length=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='withdrawal_mode',
            field=models.CharField(choices=[('D', 'DEFINITIVA'), ('E', 'EDUCACION'), ('H', 'HIPOTECARIO'), ('R', 'REPARACIONES LOCATIVAS'), ('V', 'COMPRA VIVIENDA')], max_length=1),
        ),
    ]
