"""
Django settings for centra project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--m)ne^8up&os#b_2w%_ejfxhnfwvw9k&9jq&hcmfseil18xvaz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap4',
    'authentication',
    'cesantias',
    'mathfilters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'centra.urls'
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/auth/index/'
LOGOUT_REDIRECT_URL = '/auth/login/'


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Configuración de archivos estáticos
STATIC_URL = '/static/'

# Directorios donde buscar archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Asegúrate de que esta ruta sea correcta
]

# Ubicación de los archivos estáticos recopilados
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'centra.wsgi.application'

CSRF_TRUSTED_ORIGINS = [
    'https://centra-latest.onrender.com',
]

# Carga las variables desde el archivo .env
load_dotenv()

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# variable db --https://stackpython.medium.com/how-to-start-django-project-with-a-database-postgresql-aaa1d74659d8
#DATABASES = {
#    'default': {
#        
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': os.getenv('DATABASE_NAME', 'Centra'),
#        'USER': os.getenv('DATABASE_USER', 'postgres'),
#        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'Atropos900'),
#        'HOST': os.getenv('DATABASE_HOST', 'localhost'),  # Asegúrate de que el host esté configurado como 'db'
#        'PORT': os.getenv('DATABASE_PORT', '5432'),
#    }
#}

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL')  # Render provee DATABASE_URL automáticamente
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'
USE_I18N = True
USE_L10N = True
TIME_ZONE = 'America/Bogota'
DATE_INPUT_FORMATS = ['%d/%m/%Y']
CRISPY_TEMPLATE_PACK = 'bootstrap4' 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}